Feature: remove/replace grenades/explosives from units' inventory
Crowdedlight/Crows-Zeus-Additions pull request #66
Opened 2022-08-11 18:18 UTC by Landric

Provides a module to remove grenades, launchers, and/or explosives from a given side, group, or unit.

Grenades (both smoke and explosives) can be replaced by their vanilla counterparts.

Currently does *not* set a variable on units the module has been applied to, as performance impact seems minimal.

Possible expansions: could also add an option for removing UGL ammo (and/or UGLs themselves)

2022-10-02 18:38 UTC, Crowdedlight commented
The other PR that fixes issues with loading the modules sometimes, have been merged into develop. Which creates some merge-conflicts here, mainly in "fn_zeusRegister.sqf". So please rebase/merge the latest changes into your PR.

2022-10-04 11:25 UTC, Crowdedlight requested changes
test submitting review

2022-10-04 15:11 UTC, Landric commented on CrowsZA/functions/fn_zeusRegister.sqf
> +// Collect a list of various explosives, for use in fn_stripExplosives
This snipped removed; fn_stripExplosives now uses BIS_fnc_returnParents instead of preloading all possible magazine types

2022-10-04 15:52 UTC, Landric commented on CrowsZA/functions/fn_stripExplosives.sqf
> +
Added!

2022-10-04 17:33 UTC, Crowdedlight approved these changes

2022-10-04 17:59 UTC, merged